version: "3.2"

networks:
  findchat-dev:
    driver: bridge
    driver_opts:
        com.docker.network.driver.mtu: 1450

services:
  #
  # POSTGRESQL
  #
  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: findchat
      POSTGRES_PASSWORD: hfpldfnhb
    volumes:
      - psql-data:/var/lib/postgresql/data
    networks:
      - findchat-dev
    ports:
      - "5432:5432"
  #
  # SQL WEB CLIENT
  #
#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"
#    networks:
#      - findchat-dev
  #
  # REDIS
  #
  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - findchat-dev
  #
  # FINDCHAT WEB APP
  #
  webapp:
    volumes:
      - ./backend:/app
      - ./htdocs:/htdocs
    networks:
      - findchat-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
  #
  # NGINX
  #
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/htdocs
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/cert
    networks:
      - findchat-dev
  #
  # FINDCHAT REACT APP
  #
  react:
    volumes:
      - ./frontend/src:/app/findchat-react/src
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - findchat-dev
  #
  # ELASTICSEARCH
  #
  elastic:
    build:
      context: ./elastic
      dockerfile: Dockerfile
    networks:
      - findchat-dev
    ports:
      - "9201:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
  #
  # MAILHOG
  #
  mailhog:
    image: 42bv/mailhog:latest
    ports:
      - "587:587"
      - "8025:8025"
    networks:
      - findchat-dev

  #
  # CELERY
  #
  celery:
    volumes:
      - ./backend:/app
      - ./htdocs:/htdocs
    networks:
      - findchat-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      C_FORCE_ROOT: 1
    command: celery worker -A main_app.celery_app --loglevel=DEBUG
    restart: always

  #
  # CENTRIFUGO
  #
  centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./centrifugo:/centrifugo
    networks:
      - findchat-dev
    ports:
      - "8888:8000"
    command: centrifugo --config=config.json --engine=redis --redis_api --redis_host=redis --web

volumes:
  psql-data:
    driver: local
  redis-data:
    driver: local
  elastic-data:
    driver: local


