version: "3.2"

networks:
  findchat-dev:
    driver: bridge

services:
  #
  # POSTGRESQL
  #
  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: findchat
      POSTGRES_PASSWORD: hfpldfnhb
    volumes:
      - psql-data:/var/lib/postgresql/data
    networks:
      - findchat-dev
  #
  # SQL WEB CLIENT
  #
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - findchat-dev
  #
  # REDIS
  #
  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - findchat-dev
  #
  # FINDCHAT WEB APP
  #
  webapp:
    volumes:
      - ./backend:/app
      - ./htdocs:/htdocs
    networks:
      - findchat-dev
    build:
      context: ./backend
      dockerfile: Dockerfile

  #
  # NGINX
  #
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/htdocs
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/cert
    networks:
      - findchat-dev
  #
  # FINDCHAT REACT APP
  #
  react:
#    image: findchat-react
    volumes:
      - ./frontend/src:/app/findchat-react/src
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - findchat-dev
  #
  # FINDCHAT EXPRESS FROM SSR
  #
#  express:
#    image: findchat-express
#    ports:
#      - "5000:80"
#    volumes:
#      - type: bind
#        source: ./express/src
#        target: /app/src
#      - type: bind
#        source: ./frontend/src/
#        target: /app/frontend

volumes:
  psql-data:
    driver: local
  redis-data:
    driver: local


