export const UPDATE_THREADS_POSTS = {
    REQUEST: 'UPDATE_THREADS_POSTS_REQUEST',
    SUCCESS: 'UPDATE_THREADS_POSTS_SUCCESS',
    ERROR: 'UPDATE_THREADS_POSTS_ERROR',
    FLUSH: 'UPDATE_THREADS_POSTS_FLUSH',
    APPEND_POST: 'UPDATE_THREADS_POSTS_APPEND',
};

export const UPDATE_USERS = {
    REQUEST: 'UPDATE_USERS_REQUEST',
    SUCCESS: 'UPDATE_USERS_SUCCESS',
    ERROR: 'UPDATE_USERS_ERROR'
};

export const ADD_RAW_POST = {
    REQUEST: 'ADD_RAW_POST_REQUEST',
    SUCCESS: 'ADD_RAW_POST_SUCCESS',
    ERROR: 'ADD_RAW_POST_ERROR'
};

export const UPDATE_POST_LIKES = {
    BRIEF_REQUEST: 'UPDATE_POST_LIKES_BRIEF_REQUEST',
    FULL_REQUEST: 'UPDATE_POST_LIKES_FULL_REQUEST',
    SUCCESS: 'UPDATE_POST_LIKES_SUCCESS',
    ERROR: 'UPDATE_POST_LIKES_ERROR'
};

export const UPDATE_CHAT_OFFERS = {
    SUCCESS: "UPDATE_CHAT_OFFERS_SUCCESS",
    FLUSH: "UPDATE_CHAT_OFFERS_SUCCESS"
};

// export const UPDATE_CHAT_OFFERS_FILTER = {
//     ADD_LANG: 'UPDATE_CHAT_OFFERS_FILTER_ADD_LANG',
//     REMOVE_LANG: 'UPDATE_CHAT_OFFERS_FILTER_REMOVE_LANG',
//     ADD_HASHTAG: 'UPDATE_CHAT_OFFERS_FILTER_ADD_HASHTAG',
//     REMOVE_HASHTAG: 'UPDATE_CHAT_OFFERS_FILTER_REMOVE_HASHTAG',

//     LANGUAGES: 'UPDATE_CHAT_OFFERS_FILTER_LANGUAGES',
//     HASHTAGS: 'UPDATE_CHAT_OFFERS_FILTER_HASHTAGS'
// }

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

export const UPDATE_RAW_THREADS = 'UPDATE_RAW_THREADS';
export const DELETE_RAW_THREAD = 'DELETE_RAW_THREAD';

export const SEARCH_USERS_UPDATE = 'SEARCH_USERS_UPDATE';

export const UPDATE_POST_COMPOSERS = 'UPDATE_POST_COMPOSERS';

export const UPDATE_UPLOAD_IMAGES = 'UPDATE_UPLOAD_IMAGES';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const UPDATE_UNREADED_POSTS = {
    FULL: "UPDATE_UNREADED_POSTS_FULL",
    ADD_TO_THREAD: "UPDATE_UNREADED_POSTSL_ADD_TO_THREAD",
    DEL_FROM_THREAD: "UPDATE_UNREADED_POSTS_DEL_FROM_THREAD"
};

export const UPDATE_AUTH = 'UPDATE_AUTH';